WebApp/Voupon.Rewards.WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Voupon.Common.Azure.Blob;
using Voupon.Database.Postgres.RewardsEntities;
using Voupon.Rewards.WebApp.Common.Merchants.Models;
using Voupon.Rewards.WebApp.Common.Merchants.Queries;
using Voupon.Rewards.WebApp.Common.ProductCategories.Models;
using Voupon.Rewards.WebApp.Common.Products.Models;
using Voupon.Rewards.WebApp.Common.Products.Queries;
using Voupon.Rewards.WebApp.Common.ProductSubcategories.Models;
using Voupon.Rewards.WebApp.Common.ProductSubcategories.Queries;
using Voupon.Rewards.WebApp.Models;
using Voupon.Rewards.WebApp.ViewModels;
using Voupon.Rewards.WebApp.Common.ProductCategories.Queries;
using Voupon.Rewards.WebApp.Common.ProductDiscounts.Queries;
using Voupon.Rewards.WebApp.Infrastructures.Enums;
using Voupon.Rewards.WebApp.Services.Deal.Page;
using static Voupon.Rewards.WebApp.Services.Deal.Page.DetailPage;
using Voupon.Rewards.WebApp.Common.Services.Districts.Queries;
using Voupon.Rewards.WebApp.Common.Services.Provinces.Queries;
using Voupon.Rewards.WebApp.Services.Home.Models;
using Voupon.Rewards.WebApp.Common.Services.Provinces.Models;
using Voupon.Rewards.WebApp.Services.Profile.Page;
using Voupon.Rewards.WebApp.Services.Identity.Commands;
using Voupon.Rewards.WebApp.Common.Redis.Queries;
using SendGrid;
using SendGrid.Helpers.Mail;
using Voupon.Rewards.WebApp.Services.Home.Queries;
using Voupon.Rewards.WebApp.Services.Cart.Models;
using Voupon.Database.Postgres.VodusEntities;
using Voupon.Rewards.WebApp.Services.Home.Commands;
using Voupon.Rewards.WebApp.Services.Profile.Queries;
using Voupon.Rewards.WebApp.Services.Aggregators.Queries;
using Voupon.Rewards.WebApp.Services.Ads.Queries;
using System.Xml;
using System.Xml.Linq;
using System.IO;
using Voupon.Rewards.WebApp.Services.Ads.Commands;
using RewardsAdsProduct = Voupon.Rewards.WebApp.Services.Ads.Queries.RewardsAdsProduct;
using Voupon.Rewards.WebApp.Common.ShippingCost.Models;
using Voupon.Rewards.WebApp.Common.Services.Chats.Queries;
using Microsoft.AspNetCore.Identity;
using static Voupon.Rewards.WebApp.Common.Services.Chats.Queries.GetChatMessagesByGroupIdHandler;
using Voupon.Rewards.WebApp.Common.Blob.Queries;
using Voupon.Rewards.WebApp.Common.Services.Chats.Commands;
using Voupon.Rewards.WebApp.Services.Chats.Queries;
using System.Globalization;
using Voupon.Rewards.WebApp.Infrastructures.Extensions;

namespace Voupon.Rewards.WebApp.Controllers
{
    public class HomeController : BaseController
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        //[Route("Chat")]
        //public IActionResult chat()
        //{
        //    return View();
        //}
        [HttpGet]
        [Route("chat/GetChatUsers")]
        public async Task<ApiResponseViewModel> GetChatUsers()
        {
            ApiResponseViewModel apiResponseViewModel = new ApiResponseViewModel();
            apiResponseViewModel = await Mediator.Send(new GetChatUsers() { UserId = User.Identity.GetUsername() });

            return apiResponseViewModel;
        }

        [HttpPost]
        [Route("chat/DeleteChat")]
        public async Task<ApiResponseViewModel> DeleteChat(string chatGroupId)
        {
            ApiResponseViewModel apiResponseViewModel = new ApiResponseViewModel();
            apiResponseViewModel = await Mediator.Send(new DeleteChatCommand() { ChatGroupId = chatGroupId });

            return apiResponseViewModel;
        }
        [HttpGet]
        [Route("chat/GetChatMessagesByGroupId")]
        public async Task<ApiResponseViewModel> GetChatMessagesByGroupId(string chatGroupId)
        {
            ApiResponseViewModel apiResponseViewModel = new ApiResponseViewModel();
            apiResponseViewModel = await Mediator.Send(new GetChatMessagesByGroupId() { GroupChatId = new Guid(chatGroupId) });
            var messagesList = (List<ChatMessagesViewModel>)apiResponseViewModel.Data;
            var sasTokenResult = await Mediator.Send(new SASTokenQuery());
            foreach (var message in messagesList)
            {
                if (message.IsFileAttached && sasTokenResult.Successful)
                {
                    for (int i = 0; i < message.FilesList.Count; i++)
                    {

                        if (message.FilesList[i] != "" && message.FilesList[i] != null)
                        {
                            message.FilesList[i] = message.FilesList[i] + (string)sasTokenResult.Data;
                        }

                    }
                }
            }
            return apiResponseViewModel;
        }


        [HttpGet]
        [Route("GetUnreadedMessagesCountFromUsers")]
        public async Task<ApiResponseViewModel> GetUnreadedMessagesCountFromUsers()
        {
            ApiResponseViewModel apiResponseViewModel = new ApiResponseViewModel();
            apiResponseViewModel = await Mediator.Send(new GetUnreadedMessagesCount() { UserId = User.Identity.GetUsername().ToLower() });

            return apiResponseViewModel;
        }

        [HttpGet]
        [Route("UpdateReadMessagesByGroupIdAndUserId")]
        public async Task<ApiResponseViewModel> UpdateReadMessagesByGroupIdAndUserId(string chatGroupId, string userId)
        {
            ApiResponseViewModel apiResponseViewModel = new ApiResponseViewModel();
            apiResponseViewModel = await Mediator.Send(new UpdateMessageReadStatusByGroupIdCommand() { GroupChatId = new Guid(chatGroupId), UserId = userId });
            return apiResponseViewModel;
        }

        [HttpGet]
        [Route("error/access-denied")]
        public IActionResult AccessDenied()
        {
            return View(ErrorPageEnum.ACCESS_DENIED);
        }

        [HttpGet]
        [Route("product-test-registration-old/{id}/{email}")]
        public async Task<IActionResult> ProductTestRegister(int? id, string email)
        {
            if (!id.HasValue || email == null || email == "")
            {
                return View(ErrorPageEnum.INVALID_REQUEST_PAGE);
            }

            var request = new EditPage
            {
                Email = email
            };
            var result = await Mediator.Send(request);

            if (result.AddressLine1 == null || result.City == null
                || result.CountryId == null || result.DateOfBirthDay == 0 || result.DateOfBirthMonth == 0 || result.DateOfBirthYear == 0
                || result.DemographicEducationId == 0 || result.DemographicEthnicityId == 0 || result.DemographicGenderId == 0 || result.DemographicMaritalStatusId == 0
                || result.DemographicMonthlyHouseHoldIncomeId == 0 || result.DemographicMonthlyIncomeId == 0 || result.DemographicStateId == 0
                || result.FirstName == "" || result.LastName == "" || result.FirstName == null || result.LastName == null || result.MobileCountryCode == null || result.MobileNumber == null
                || result.Postcode == null)
            {
                return RedirectToAction("Edit", "Profile", new { from = "ProductTestRegister", productId = id.Value, email = email });
            }

            HUTSurveyProjects surveyProjectDetails = new HUTSurveyProjects();
            ApiResponseViewModel response = await Mediator.Send(new GetHUTSurveyProjectDetailsById() { Id = id.Value });
            if (response.Successful)
            {
                surveyProjectDetails = (HUTSurveyProjects)response.Data;
            }
            else
            {

            }
            ApiResponseViewModel isExistParticipantresponse = await Mediator.Send(new IsParticipantEmail() { Id = id.Value, Email = email });
            ProductTestRegisterModel productTestRegisterModel = new ProductTestRegisterModel();
            if (result.AddressLine2 != "" && result.AddressLine2 != null)
            {
                productTestRegisterModel.MasterMemberProfileAddress = result.AddressLine1 + ", " + result.AddressLine2 + ", " + result.Postcode + ", " + result.City + ", " + result.State;
            }
            else
            {
                productTestRegisterModel.MasterMemberProfileAddress = result.AddressLine1 + ", " + result.Postcode + ", " + result.City + ", " + result.State;
            }

            productTestRegisterModel.MasterMemberProfileEmail = result.Email;
            productTestRegisterModel.MasterMemberProfileId = result.Id;

            productTestRegisterModel.SurveyProjectStatus = surveyProjectDetails.IsActive;
            productTestRegisterModel.Reward = surveyProjectDetails.VPointsReward;
            productTestRegisterModel.SurveyProjectName = surveyProjectDetails.ExternalName;
            productTestRegisterModel.SurveyProjectId = surveyProjectDetails.Id;
            productTestRegisterModel.SurveyProjectStartDate = surveyProjectDetails.StartDate.Value;
            productTestRegisterModel.IsParticipantEmail = (bool)isExistParticipantresponse.Data;

            return View(productTestRegisterModel);
        }

        [HttpPost]
        [Route("RegisterParticipantForTest-old")]
        public async Task<ApiResponseViewModel> RegisterParticipantForTest(int projectId, string address, string email)
        {
            ApiResponseViewModel response = await Mediator.Send(new UpdateParticipantDetalsFromMasterProfile() { Id = GetMasterMemberId(Request.HttpContext), ProjectId = projectId, Address = address, Email = email });

            return response;
        }
        [HttpPost]
        [Route("SendVerificationEmailAsync")]
        public async Task<JsonResult> SendVerificationEmailAsync(string email, string from)
        {
            var apiResponse = new ApiResponseViewModel();
            if (email == null || email == "")
            {
                apiResponse.Message = "Invalid request [001]";

WebApp/Voupon.Rewards.WebApp/Controllers/IdentityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Voupon.Rewards.WebApp.Infrastructures.Extensions;
using Voupon.Rewards.WebApp.Services.Identity.Commands;
using Voupon.Rewards.WebApp.Services.Identity.Commands.Create;
using static Voupon.Rewards.WebApp.Services.Identity.Commands.Create.CreateAccountCommand;
using static Voupon.Rewards.WebApp.Services.Identity.Commands.EmailLoginCommand;

namespace Voupon.Rewards.WebApp.Controllers
{
    public class IdentityController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Validate([FromForm]EmailLoginCommand command)
        {
            command.HttpDTO = new HttpDTO();
            command.HttpDTO.Origin = Request.Headers["Origin"];
            command.HttpDTO.UserAgent = Request.Headers["User-Agent"];
            command.HttpDTO.Host = Request.Headers["Host"];
            command.HttpDTO.Referer = Request.Headers["Referer"];
            var result = await Mediator.Send(command);

            if (result.Successful)
            {
                var loginResponseViewModel = (LoginResponseViewModel)result.Data;
                var cookieOptions = new Microsoft.AspNetCore.Http.CookieOptions()
                {
                    Path = "/",
                    Expires = DateTime.Now.AddDays(365000),
                    SameSite = Microsoft.AspNetCore.Http.SameSiteMode.None,
                    Secure = true
                };
                if (loginResponseViewModel.PreferredLanguage != null)
                {
                    HttpContext.Response.Cookies.Append("Vodus.Language", loginResponseViewModel.PreferredLanguage, cookieOptions);
                }

                HttpContext.Response.Cookies.Append("Rewards.Temporary.Points", loginResponseViewModel.Points.ToString(), cookieOptions);
                HttpContext.Response.Cookies.Append("Rewards.Account.Email", Uri.UnescapeDataString(loginResponseViewModel.Email), cookieOptions);
                return Ok(result);
            }

            return BadRequest(result.Message);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAccount(CreateAccountCommand command)
        {

            var result = await Mediator.Send(command);

            if (result.Successful)
            {
                var loginCommand = new EmailLoginCommand();
                loginCommand.HttpDTO = new HttpDTO();
                loginCommand.HttpDTO.Origin = Request.Headers["Origin"];
                loginCommand.HttpDTO.UserAgent = Request.Headers["User-Agent"];
                loginCommand.HttpDTO.Host = Request.Headers["Host"];
                loginCommand.HttpDTO.Referer = Request.Headers["Referer"];
                loginCommand.Email = command.Email;
                loginCommand.Password = command.Password;
                var loginResult = await Mediator.Send(loginCommand);

                if (loginResult.Successful)
                {
                    var loginResponseViewModel = (LoginResponseViewModel)loginResult.Data;
                    var cookieOptions = new Microsoft.AspNetCore.Http.CookieOptions()
                    {
                        Path = "/",
                        Expires = DateTime.Now.AddDays(365000),
                        SameSite = Microsoft.AspNetCore.Http.SameSiteMode.None,
                        Secure = true
                    };
                    if (loginResponseViewModel.PreferredLanguage != null)
                    {
                        HttpContext.Response.Cookies.Append("Vodus.Language", loginResponseViewModel.PreferredLanguage, cookieOptions);
                    }

                    HttpContext.Response.Cookies.Append("Rewards.Temporary.Points", loginResponseViewModel.Points.ToString(), cookieOptions);
                    HttpContext.Response.Cookies.Append("Rewards.Account.Email", Uri.UnescapeDataString(loginResponseViewModel.Email), cookieOptions);
                    return Ok(result);
                }

                return Ok(result);
            }
            return BadRequest(result.Message);
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePassword(UpdatePasswordCommand command)
        {
            command.UserId = User.Identity.GetAccountUserId();
            var result = await Mediator.Send(command);
            if (result.Successful)
            {
                return Ok(result);
            }
            // var apiResponse = new ApiResponse();
            return BadRequest(result.Message);
        }

        [HttpPost]
        public async Task<IActionResult> SendResetLink(SendResetLinkCommand command)
        {
            var result = await Mediator.Send(command);
            return Ok(result);
        }

        [HttpPost]
        public async Task<IActionResult> ResetPassword(ResetPasswordCommand command)
        {
            var result = await Mediator.Send(command);
            if (result.Successful)
            {
                return Ok(result);
            }
            return BadRequest(result.Message);
        }

        [HttpGet]
        public async Task<IActionResult> Google(ExchangeGoogleCodeForAccessTokenCommand command)
        {
            return View();
        }

    }
}

WebApp/Voupon.Rewards.WebApp/Views/Home/ActivationFailed.cshtml
@{
    ViewData["Title"] = "ActivationFailed";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="passwordBox animated fadeInDown">
    <div class="row" id="forgetPasswordContainer">

        <div class="col-md-12">
            <div class="ibox-content">
                <h2 class="font-bold">Activation failed</h2>
                <p class="alert alert-danger fail-message">
                </p>
                <a href="@Url.Action("Index","Home")" type="button" class="btn btn-primary block full-width m-b" id="btnSendResetLink">Back to home page</a>
            </div>
        </div>
    </div>
    <div class="row" id="forgetPasswordSuccessfulContainer" style="display:none;">
        <p class="alert alert-success" id="resetLink"></p>
    </div>
</div>

@section scripts
{

    <script>

        $(function () {
            var failMessage = getParameterByName("from");
            $(".fail-message").html(failMessage)
      $("#btnSendResetLink").click(function (e) {
        toastr.clear();
        var email = $("#email").val();
        if (email != "") {
          $.ajax({
            global: true,
            type: 'POST',
            dataType: 'json',
            data: { email: email },
            url: "@Url.Action("SendResetLink", "Identity")",
            success: function (response) {
              if (response.successful) {
                $("#forgetPasswordContainer").css("display", "none");
                $("#forgetPasswordSuccessfulContainer").css("display", "block");
                $("#resetLink").html("A reset link have been sent to your email: <strong>" + email + "</strong>");
              }
              else {
                  $(".toast-warning").remove();
                toastr.clear();
                toastr.error(response.message);
              }
            },
            error: function () {
                $(".toast-warning").remove();
            }
          });
        }
        else {
          toastr.error("Email is required");
        }
      });

    });
    </script>
}

WebApp/Voupon.Rewards.WebApp/Views/Home/Chat.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
<html>

<body>
    <h1>Azure SignalR Serverless Sample</h1><br />
    <div id="messages"></div>
    <div class="container">
        <div class="row">&nbsp;</div>
        <!--<div class="row">
            <div class="col-2">Sender</div>
            <div class="col-4"><input type="text" id="senderInput" /></div>
        </div>-->
        <div class="row">
            <div class="col-2">Receiver</div>
            <div class="col-4"><input type="text" id="receiverInput" /></div>
        </div>
        <div class="row">
            <div class="col-2">Message</div>
            <div class="col-4"><input type="text" id="messageInput" /></div>
        </div>
        <div class="row">&nbsp;</div>
        <div class="row">
            <div class="col-6">
                <input type="button" id="sendButton" value="Send Message" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <ul id="messagesList"></ul>
        </div>
    </div>
    @section scripts{

        <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/6.0.0-rc.1.21452.15/signalr.min.js"></script>
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    }
    <script>
    function initialize() {
        axios.get('http://localhost:7071' + "/api/negotiate", {
            headers: { 'x-ms-client-principal-id': "@ViewData["AccountEmail"]" + "_v"/*, 'Authorization': vodusRewardReadCookie("Vodus.Token")*/ }
        }).then(response => {
            const options = {
                accessTokenFactory: () => response.data.accessToken
            }
           const connection = new signalR.HubConnectionBuilder()
                .withUrl(response.data.url, options)
                .build(signalR.HttpTransportType.None)

            connection.on('newMessage', (message) => {
                console.log(message);
                document.getElementById("messages").innerHTML = document.getElementById("messages").innerHTML + "<br/>" + message.Sender + ": " + message.Text;
            });
            connection.onclose(() => console.log('disconnected'));
            console.log('connecting...');

            connection.start({ withCredentials: true })
                .then(() => console.log('ready...'))
                .catch(console.error);
        });

        document.getElementById("sendButton").addEventListener("click", function (event) {
            axios.post('http://localhost:7071' + "/api/SendMessage", {
                Message: {
                    Sender: "@ViewData["AccountEmail"]",
                    Text: document.getElementById("messageInput").value
                } , UserId: document.getElementById("receiverInput").value
            });
        });
    }

        $(document).ready(function () {
            initialize();

        });


    </script>
    <script></script>
</body>

</html>

WebApp/Voupon.Rewards.WebApp/Views/Home/FAQ.cshtml
@{
    ViewData["Title"] = "FAQ";
    ViewBag.Description = "Find the Answers to the Most Popular Questions Asked in our FAQ Section. From Delivery Times to Payment Options, We’ve Got it All Covered. ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row mt-4" style="max-width:1200px;">
    <h1 class="col-12">
            <b>Frequently Asked Questions (FAQ)</b>
    </h1>

    <br />

    <div class="col-lg-7 faq-container">
        <h2>
            Delivery
        </h2>
        <div class="faq-item">
            <h3>
                1. When will I receive my item?
            </h3>
            <p>
                All orders are processed within 2-3 business days. Orders are not shipped or delivered on weekends or holidays.
                <br /><br />
                Estimated order delivery times are 4 to 14 days from the date of purchase.
            </p>
        </div>
        <div class="faq-item">
            <h3>
                2. How can I track my item?
            </h3>
            <p style="margin-bottom:0;">
                You may track your item by doing the following process:
            </p>
            <ol>
                <li>
                    Login to your account on Vodus.
                </li>
                <li>
                    Go to <a href="/order/history">My Purchases</a> to view your orders.
                </li>
                <li>
                    Find your order and click on the down arrow button.
                </li>
                <li>
                    You will find your tracking number on the pop-up modal if the merchant has shipped your item.
                </li>
            </ol>
        </div>

        <div class="faq-item">
            <h3>
                3. What can I do if the merchant have not shipped my items after 3 days?
            </h3>
            <p>
                If the merchant did not update the delivery status or input any the tracking number for your order after 3 days, you may contact Vodus to request for refund for your order.
            </p>
        </div>
        <div class="faq-item">
            <h3>
                4. What can I do if I have not received your order after 14 days?
            </h3>
            <p>
                If you have not received an order after 14 days,
                you should track your product using the tracking number provided by the merchant or contact your merchant about the delivery.
            </p>
        </div>
    </div>

    <div class="col-lg-5 contact-form-faq">
        <div class="contact-form">
            <h2>
                Can’t find what you are looking for? <br />
                Submit a request.
            </h2>
            <br />
            <div class="row placeholder-white">
                <div class="col-12"> <input id="txtContactName" type="text" class="form-control" placeholder="Your Name"></div>
            </div>
            <div class="row placeholder-white">
                <div class="col-12"> <input id="txtContactEmailAddress" type="text" class="form-control" placeholder="Email Address"></div>
            </div>
            <div class="row">
                <div class="col-12 placeholder-white"> <input id="txtContactSubject" type="text" class="form-control" placeholder="Subject"></div>
            </div>
            <div class="row">
                <div class="col-12">
                    <textarea class="form-control" id="txtContactSMessage" rows="6" placeholder="Your Message"></textarea>
                </div>
            </div>
            <div class="row">
                <div class="col-12" style="text-align:right;">
                    <btn class="btn btn-primary" id="btnSubmitMessage">Submit</btn>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#btnSubmitMessage").click(function () {
            if ($("#txtContactName").val() == "" || $("#txtContactEmailAddress").val() == "" || $("#txtContactSubject").val() == "" || $("#txtContactSMessage").val()=="") {
                 toastr.error("Please enter all your details above to submit your request.");
                return;
            }
            $("#btnSubmitMessage").css("pointer-events", "none");
            $("#btnSubmitMessage").html("Submitting");
            $.ajax({
                global: false,
                type: 'POST',
                dataType: 'json',
                data: {
                    "name": $("#txtContactName").val(),
                    "email": $("#txtContactEmailAddress").val(),
                    "subject": $("#txtContactSubject").val(),
                    "message": $("#txtContactSMessage").val()
                },
                url: "/SubmitNewRequestNoRec",
                success: function (response) {
                    if (response.successful) {
                        toastr.success(response.message);
                        $("#btnSubmitMessage").html("Submitted");
                    }
                    else {
                        toastr.clear();
                        toastr.error(response.message);
                        $("#btnSubmitMessage").css("pointer-events", "auto");
                        $("#btnSubmitMessage").html("Submit");
                    }
                    $(".toast-warning").remove();
                },
                error: function () {
                    toastr.clear();
                    toastr.error("Something went wrong.");
                    $("#btnSubmitMessage").css("pointer-events", "auto");
                    $("#btnSubmitMessage").html("Submit");
                }
            });
        });
    });
</script>

WebApp/Voupon.Rewards.WebApp/Views/Home/ProductTest.cshtml
@{
    ViewData["Title"] = "ProductTest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>ProductTest</h1>

<!-- Normal form embed code, add an ID -->
<iframe id="gform" src="https://docs.google.com/forms/d/e/1FAIpQLSfVBnK1jI7v2nYtYCV9-AAi2Wqr37ARvwmk9HjBAZkrW5tTNQ/viewform?fbzx=6074573064717870278" width="640" height="487" frameborder="0" marginheight="0" marginwidth="0" style="margin:0 auto; max-width:100%;">Loading…</iframe>

<script type="text/javascript">
    var load = 0;

    document.getElementById('gform').onload = function () {
        /*Execute on every reload on iFrame*/
        load++;
        if (load > 1) {
            /*Second reload is a submit*/
            //document.location = "https://www.google.com/search?q=thanks&tbm=isch";
            alert("first google Form submitted ");
        }
    }
</script>

WebApp/Voupon.Rewards.WebApp/Views/Home/ResetPassword.cshtml
@model Voupon.Rewards.WebApp.Services.Identity.Commands.ResetPasswordViewModel

@{
    ViewBag.Title = "Change Password";
}

<form id="changePasswordForm" name="changePasswordForm">
    <div class="row">
        <div class="col-12">
            <h2><strong>Change Password</strong></h2>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-lg-4">
        </div>
        <div class="col-lg-12">
            @Html.HiddenFor(x => x.Code, new { @class = "form-control" })
            <div class="form-group">
                <label><strong>Email</strong></label>
                @Html.TextBoxFor(x => x.Email, new { @class = "form-control", disabled = "disabled" })
            </div>
            <div class="form-group">
                <label style="margin-bottom:0;"><strong>New Password</strong></label>
                <p style="font-size:14px;margin-bottom:10px;">Your password should contain at least 8 characters, an uppercase, lowercase, number and special character.</p>
                @Html.PasswordFor(x => x.NewPassword, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.NewPassword, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label><strong>Re-Confirm New Password</strong></label>
                @Html.PasswordFor(x => x.ConfirmPassword, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-lg-4">
        </div>
    </div>
    <div class="row">
        <div class="col-l2">
            <p>
                
            </p>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-lg-12">
            <button type="button" class="btn btn-primary" id="btnUpdatePassword">Update</button>
        </div>
    </div>
</form>

@section scripts
{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @*<script src="@Url.Content("/Scripts/jquery.validate.min.js")"></script>
        <script src="@Url.Content("/Scripts/jquery.validate.unobtrusive.min.js")"></script>*@
    <script>

    $(document).ready(function () {

      $("#btnUpdatePassword").on("click", function () {

        if ($("#changePasswordForm").valid()) {

          $("#Email").removeAttr("disabled");
          var data = $("#changePasswordForm").serialize();

            toastr.warning("Loading...");
          $.ajax({
            global: false,
            type: 'POST',
            dataType: 'json',
            data: data,
            url: "@Url.Action("ResetPassword", "Identity")",
              success: function (response) {                 
              if (response.successful) {
                  toastr.success(response.message);
                  setTimeout(function(){ document.location.href="/"; },3000);
                  
              }
              else {
                toastr.clear();
                toastr.error(response.message);
              }
              $(".toast-warning").remove();
            },
            error: function (res) {
                toastr.clear();
                toastr.error(res.responseText);
              $(".toast-warning").remove();
            }
          });

          $("#Email").attr("disabled", "");
        }
      })
    })

    </script>
}