WebApp/Voupon.Merchant.WebApp/Areas/Admin/Controllers/EditProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Voupon.Merchant.WebApp.Infrastructure.Enums;
using Voupon.Merchant.WebApp.Services.Profile.Page;
using Voupon.Merchant.WebApp.Services.Identity.Commands.Update;
using Voupon.Merchant.WebApp.Controllers;

namespace Voupon.Merchant.WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/[controller]")]
    [Authorize(Roles = "Admin")]
    public class EditProfileController : BaseController
    {      
        public async Task<IActionResult> Index()
        {
            var request = new ResetPasswordPage
            {
                Email = User.Identity.Name
            };
            var result = await Mediator.Send(request);
            result.OldPassword = "";
            if (string.IsNullOrEmpty(result.Email))
            {
                return View(ErrorPageEnum.INVALID_REQUEST_PAGE);
            }
            return View(result);
        }

        [Route("UpdatePassword")]  
        public async Task<IActionResult> UpdatePassword(ResetPasswordCommand command)
        {
            command.Email = User.Identity.Name;
            var result = await Mediator.Send(command);

            if (result.Successful)
            {
                return Ok(result);
            }
            return BadRequest(result.Message);
        }

    }
}

WebApp/Voupon.Merchant.WebApp/Areas/App/Controllers/EditProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Voupon.Merchant.WebApp.Infrastructure.Enums;
using Voupon.Merchant.WebApp.Services.Profile.Page;
using Voupon.Merchant.WebApp.Services.Identity.Commands.Update;
using Voupon.Merchant.WebApp.Controllers;

namespace Voupon.Merchant.WebApp.Areas.App.Controllers
{
    [Area("App")]
    [Route("App/[controller]")]
    [Authorize(Roles = "Merchant,Staff")]
    public class EditProfileController : BaseController
    {      
        public async Task<IActionResult> Index()
        {
            var request = new ResetPasswordPage
            {
                Email = User.Identity.Name
            };
            var result = await Mediator.Send(request);
            result.OldPassword = "";
            if (string.IsNullOrEmpty(result.Email))
            {
                return View(ErrorPageEnum.INVALID_REQUEST_PAGE);
            }
            return View(result);
        }

        [Route("UpdatePassword")]
     //   [Authorize(Roles = "Merchant")]

        public async Task<IActionResult> UpdatePassword(ResetPasswordCommand command)
        {
            command.Email = User.Identity.Name;
            var result = await Mediator.Send(command);

            if (result.Successful)
            {
                return Ok(result);
            }
            return BadRequest(result.Message);
        }

    }
}

WebApp/Voupon.Merchant.WebApp/Areas/App/Views/EditProfile/Index.cshtml
@model Voupon.Merchant.WebApp.Services.Profile.Page.ChangePasswordViewModel

@{
    ViewBag.Title = "Change Password";
}

<div class="dashboard-main-wrapper">
    <div class="container-fluid dashboard-content merchant-dashboard">
        <form id="changePasswordForm" name="changePasswordForm" style="text-align: -webkit-center;">
            <div class="align-center mb-3">
                <h2>Update Password</h2>
            </div>
            <div class="row" style="max-width:500px">
                <div class="col-lg-4">
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        @Html.LabelFor(x => x.Email)
                        @Html.TextBoxFor(x => x.Email, new { @class = "form-control", disabled = "disabled" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.OldPassword)
                        @Html.PasswordFor(x => x.OldPassword, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.OldPassword, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.NewPassword)
                        @Html.PasswordFor(x => x.NewPassword, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.NewPassword, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.ConfirmPassword)
                        @Html.PasswordFor(x => x.ConfirmPassword, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.ConfirmPassword, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-4">
                </div>
            </div>
            <div class="row text-center mb-2">
                <div class="col-lg-12">
                    <button type="button" class="btn btn-primary" id="btnUpdatePassword">Update</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script>

    $("#btnUpdatePassword").on("click", function () {

    if ($("#changePasswordForm").valid()) {

    $("#Email").removeAttr("disabled");
    var data = $("#changePasswordForm").serialize();

    $("#loading").show();
    $.ajax({
    global: false,
    type: 'POST',
    dataType: 'json',
    data: data,
    url: "@Url.Action("UpdatePassword", "EditProfile")",
    success: function (response) {
    console.log(response);
    if (response.successful) {
    toastr.success(response.message);
    setTimeout(function () { document.location.href = "/"; }, 3000);
    }
    else {
    toastr.clear();
    toastr.error(response.message);
    }
    $("#loading").hide();
    },
    error: function (res) {
    toastr.clear();
    toastr.error(res.responseText);
    $("#loading").hide();
    }
    });

    $("#Email").attr("disabled", "");
    }
    });

    </script>
}